### ISSUE TITLE
Get-RabbitMQQueue walkthrough errors

### ISSUE THREAD

**Issue by rhmoult** [RamblingCookieMonster/RabbitMQTools#21]
Hi, I'm on a 32 bit Windows 7 SP1 box with PS 5 installed (CLR 4.0.30319.18444), and I'm having difficulty with your walkthrough.  Everything is fine up until I try to get the RabbitMQQueue.  Everything from that point on just gives me errors as demonstrated below.

I was able to verify via Python that my Exchange and Queue were set up and that my message is making it into the queue, but trying to use Get-RabbitMQQueue or Get-RabbitMQQueueBinding fails as shown:

![sillyrabbittools](https://cloud.githubusercontent.com/assets/7614599/16694917/f846ef1c-450a-11e6-9195-db879692c116.png)

I'd much appreciate any insight you can give me.

**Comment by gaelcolas** [comment]
Hi, I think that's an issue with your version of RabbitMQ, this error also happen with the Management UI.
In short, you're running a version of RabbitMQ < 3.6.4 with Erlang 19 (but only Erl 18 is supported).
https://github.com/rabbitmq/rabbitmq-management/issues/244

I fixed that issue by running:
`Install-Package RabbitMq -RequiredVersion 3.6.4 -ProviderName Chocolatey`
You have to specify the version because the package is (as of yesterday), not approved yet by the Choco maintainers.

**Comment by gaelcolas** [comment]
@RamblingCookieMonster I think you can close this :)

**Comment by RamblingCookieMonster** [comment]
Whee going through old issues, closing this out - cheers!
